version: "3.9"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web_app
        ports:
            - "5000:5000"
        environment:
            - FLASK_ENV=development
        depends_on:
            - db

    db:
        image: postgres:14
        container_name: postgres_db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydatabase
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
